version: '3.8'

services:
  web:
    build: .
    container_name: mickblog
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./site_config.md:/app/site_config.md
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - db
    networks:
      - mickblog_network

  db:
    image: postgres:14-alpine
    container_name: mickblog_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.docker
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - mickblog_network

  nginx:
    image: nginx:alpine
    container_name: mickblog_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/nginx/ssl
    depends_on:
      - web
    networks:
      - mickblog_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  mickblog_network:
    driver: bridge