# Generated by Django 5.1.7 on 2025-03-14 23:46

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mick Blog', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('brand', models.CharField(default='MB', max_length=10)),
                ('primary_color', models.CharField(default='#007bff', max_length=20)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=20)),
                ('favicon', models.ImageField(blank=True, upload_to='site/')),
                ('logo', models.ImageField(blank=True, upload_to='site/')),
                ('about_text', markdownx.models.MarkdownxField(blank=True)),
                ('footer_text', models.CharField(blank=True, max_length=500)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('meta_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
