# Generated by Django 5.1.7 on 2025-03-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='bluesky_url',
            field=models.URLField(blank=True),
        ),
    ]
