# Generated by Django 5.1.7 on 2025-03-17 23:17

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfig_bluesky_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='anthropic_api_key',
            field=models.CharField(blank=True, help_text='Anthropic API key for AI-powered site configuration editor', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_text',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Content for About page in Markdown format'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='bluesky_url',
            field=models.URLField(blank=True, help_text='Bluesky profile URL'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='brand',
            field=models.CharField(default='MB', help_text='Short text or acronym for navbar brand', max_length=10),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='email',
            field=models.EmailField(blank=True, help_text='Public contact email', max_length=254),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook profile URL'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Site favicon', upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='footer_text',
            field=models.CharField(blank=True, help_text='Text displayed in page footer', max_length=500),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile URL'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Google Analytics tracking ID', max_length=50),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text='Site logo', upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Enable maintenance mode for the site'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description for the site'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='phone',
            field=models.CharField(blank=True, help_text='Public contact phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='primary_color',
            field=models.CharField(default='#007bff', help_text='Main color theme (hex code)', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='secondary_color',
            field=models.CharField(default='#6c757d', help_text='Secondary color theme (hex code)', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short description shown on homepage', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='title',
            field=models.CharField(default='Mick Blog', help_text='Main site title used in browser tab and header', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL'),
        ),
    ]
