# Generated by Django 5.1.7 on 2025-03-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_increase_api_key_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='anthropic_api_key',
            field=models.CharField(blank=True, help_text='Anthropic API key for AI-powered site configuration editor - usually 83 characters or longer', max_length=255, null=True),
        ),
    ]
