# Generated by Django 5.1.7 on 2025-03-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_siteconfig_anthropic_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='anthropic_api_key',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Custom CSS to be applied to the entire site'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this configuration was last updated'),
        ),
    ]
